SRC += oneshot.c

KEY_OVERRIDE_ENABLE = yes
BOOTLOADER = atmel-dfu
MOUSEKEY_ENABLE = no
COMBO_ENABLE = no
TAP_DANCE_ENABLE = no
CONSOLE_ENABLE = no
DYNAMIC_MACRO_ENABLE = yes
UNICODEMAP_ENABLE = no
UNICODE_ENABLE = no
