SRC += oneshot.c

BOOTLOADER = atmel-dfu

MOUSEKEY_ENABLE = no
COMBO_ENABLE = no
TAP_DANCE_ENABLE = no
CONSOLE_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = no
UNICODEMAP_ENABLE = no
UNICODE_ENABLE = no
